version: '3.8'
services:
  db:
    container_name: pg_container
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: task-management
    ports:
      - '54321:5432'

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - '5050:80'
    depends_on:
      - db

  nestjs:
    build: ./
    command: npm run start:dev
    restart: unless-stopped
    ports:
      - '5000:5000'
    depends_on:
      - db
    volumes:
      # - .:/nestjs
      - ./node_modules:/nestjs/node_modules
      - ./src:/nestjs/src

volumes:
  db:
